export const layersInitialState = [
    {
        index: 0,
        label: "DEF",
        bindings: [
            {
                index: 0,
                label: "q",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 1,
                label: "w",
                tapped: {
                    code: "W",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [
                        {
                            id: 6001,
                            key_category_id: 63,
                            code: "LS",
                            label: "Left Shift",
                        },
                    ],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 2,
                label: "e",
                tapped: {
                    code: "E",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [
                        {
                            id: 6003,
                            key_category_id: 63,
                            code: "LC",
                            label: "Left Ctrl",
                        },
                    ],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 3,
                label: "r",
                tapped: {
                    code: "R",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [
                        {
                            id: 6005,
                            key_category_id: 63,
                            code: "LA",
                            label: "Left Alt",
                        },
                    ],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 4,
                label: "t",
                tapped: {
                    code: "T",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [
                        {
                            id: 6007,
                            key_category_id: 63,
                            code: "LG",
                            label: "Left Gui",
                        },
                    ],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 5,
                label: "y",
                tapped: {
                    code: "Y",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 6,
                label: "u",
                tapped: {
                    code: "U",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 7,
                label: "i",
                tapped: {
                    code: "I",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 8,
                label: "o",
                tapped: {
                    code: "O",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 9,
                label: "p",
                tapped: {
                    code: "P",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 10,
                label: "a",
                tapped: {
                    code: "A",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 11,
                label: "s",
                tapped: {
                    code: "S",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [
                        {
                            id: 6001,
                            key_category_id: 63,
                            code: "LS",
                            label: "Left Shift",
                        },
                        {
                            id: 6003,
                            key_category_id: 63,
                            code: "LC",
                            label: "Left Ctrl",
                        },
                    ],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 12,
                label: "d",
                tapped: {
                    code: "D",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [
                        {
                            id: 6001,
                            key_category_id: 63,
                            code: "LS",
                            label: "Left Shift",
                        },
                        {
                            id: 6005,
                            key_category_id: 63,
                            code: "LA",
                            label: "Left Alt",
                        },
                    ],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 13,
                label: "f",
                tapped: {
                    code: "F",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [
                        {
                            id: 6001,
                            key_category_id: 63,
                            code: "LS",
                            label: "Left Shift",
                        },
                        {
                            id: 6007,
                            key_category_id: 63,
                            code: "LG",
                            label: "Left Gui",
                        },
                    ],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 14,
                label: "g",
                tapped: {
                    code: "G",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [
                        {
                            id: 6001,
                            key_category_id: 63,
                            code: "LS",
                            label: "Left Shift",
                        },
                        {
                            id: 6003,
                            key_category_id: 63,
                            code: "LC",
                            label: "Left Ctrl",
                        },
                        {
                            id: 6005,
                            key_category_id: 63,
                            code: "LA",
                            label: "Left Alt",
                        },
                        {
                            id: 6007,
                            key_category_id: 63,
                            code: "LG",
                            label: "Left Gui",
                        },
                    ],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 15,
                label: "h",
                tapped: {
                    code: "H",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 16,
                label: "j",
                tapped: {
                    code: "J",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 17,
                label: "k",
                tapped: {
                    code: "K",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 18,
                label: "l",
                tapped: {
                    code: "L",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 19,
                label: ":",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 20,
                label: "z",
                tapped: {
                    code: "Z",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 21,
                label: "x",
                tapped: {
                    code: "X",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 22,
                label: "c",
                tapped: {
                    code: "C",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 23,
                label: "v",
                tapped: {
                    code: "V",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 24,
                label: "b",
                tapped: {
                    code: "B",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 25,
                label: "n",
                tapped: {
                    code: "N",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 26,
                label: "m",
                tapped: {
                    code: "M",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 27,
                label: ",",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 28,
                label: ".",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 29,
                label: "/",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 30,
                label: "1",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 31,
                label: "2",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 32,
                label: "3",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 33,
                label: "4",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 34,
                label: "5",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 35,
                label: "6",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
        ],
    },
    {
        index: 1,
        label: "NAV",
        bindings: [
            {
                index: 0,
                label: "1",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 1,
                label: "2",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 2,
                label: "3",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 3,
                label: "r",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 4,
                label: "t",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 5,
                label: "y",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 6,
                label: "u",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 7,
                label: "i",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 8,
                label: "o",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 9,
                label: "p",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 10,
                label: "a",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 11,
                label: "s",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 12,
                label: "d",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 13,
                label: "f",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 14,
                label: "g",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 15,
                label: "h",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 16,
                label: "j",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 17,
                label: "k",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 18,
                label: "l",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 19,
                label: ":",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 20,
                label: "z",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 21,
                label: "x",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 22,
                label: "c",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 23,
                label: "v",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 24,
                label: "b",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 25,
                label: "n",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 26,
                label: "m",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 27,
                label: ",",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 28,
                label: ".",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 29,
                label: "/",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 30,
                label: "1",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 31,
                label: "2",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 32,
                label: "3",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 33,
                label: "4",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 34,
                label: "5",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 35,
                label: "6",
                tapped: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
        ],
    },
];
