export const layersInitialState = [
    {
        index: 0,
        label: "DEF",
        /* bindings: `
     &none   &kp Q &kp W &kp E &kp R &kp T          &kp Y &kp U  &kp I    &kp O   &kp P    &none
     &none   &kp A &kp S &kp D &hm LCMD F &kp G     &kp H &hm LCMD J  &kp K     &kp L   &kp SEMI     &none
     &none   &kp Z &kp X &kp C &kp V &kp B          &kp N &kp M  &kp COMMA &kp DOT   &kp FSLH    &none 
                  &kp LSHIFT  &kp SPACE &kp N3      &to ARROWS_L  &kp ENTER  &kp BACKSPACE
                  `,
                  */
        bindings: [
            {
                index: 0,
                label: "q",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 1,
                label: "w",
                tapped: {
                    code: "&kp W",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 2,
                label: "e",
                tapped: {
                    code: "&kp E",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 3,
                label: "r",
                tapped: {
                    code: "&kp R",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 4,
                label: "t",
                tapped: {
                    code: "&kp T",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 5,
                label: "y",
                tapped: {
                    code: "&kp Y",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 6,
                label: "u",
                tapped: {
                    code: "&kp U",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 7,
                label: "i",
                tapped: {
                    code: "&kp I",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 8,
                label: "o",
                tapped: {
                    code: "&kp O",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 9,
                label: "p",
                tapped: {
                    code: "&kp P",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 10,
                label: "a",
                tapped: {
                    code: "&kp A",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 11,
                label: "s",
                tapped: {
                    code: "&kp S",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 12,
                label: "d",
                tapped: {
                    code: "&kp D",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 13,
                label: "f",
                tapped: {
                    code: "&kp F",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 14,
                label: "g",
                tapped: {
                    code: "&kp G",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 15,
                label: "h",
                tapped: {
                    code: "&kp H",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 16,
                label: "j",
                tapped: {
                    code: "&kp J",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 17,
                label: "k",
                tapped: {
                    code: "&kp K",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 18,
                label: "l",
                tapped: {
                    code: "&kp L",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 19,
                label: ":",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 20,
                label: "z",
                tapped: {
                    code: "&kp Z",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 21,
                label: "x",
                tapped: {
                    code: "&kp X",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 22,
                label: "c",
                tapped: {
                    code: "&kp C",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 23,
                label: "v",
                tapped: {
                    code: "&kp V",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 24,
                label: "b",
                tapped: {
                    code: "&kp B",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 25,
                label: "n",
                tapped: {
                    code: "&kp N",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 26,
                label: "m",
                tapped: {
                    code: "&kp M",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 27,
                label: ",",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 28,
                label: ".",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 29,
                label: "/",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 30,
                label: "1",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 31,
                label: "2",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 32,
                label: "3",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 33,
                label: "4",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 34,
                label: "5",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 35,
                label: "6",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
        ],
    },
    {
        index: 1,
        label: "NAV",
        /* bindings: `
     &none   &kp Q &kp W &kp E &kp R &kp T          &kp Y &kp U  &kp I    &kp O   &kp P    &none
     &none   &kp A &kp S &kp D &hm LCMD F &kp G     &kp H &hm LCMD J  &kp K     &kp L   &kp SEMI     &none
     &none   &kp Z &kp X &kp C &kp V &kp B          &kp N &kp M  &kp COMMA &kp DOT   &kp FSLH    &none 
                  &kp LSHIFT  &kp SPACE &kp N3      &to ARROWS_L  &kp ENTER  &kp BACKSPACE
                  `,
                    */
        bindings: [
            {
                index: 0,
                label: "1",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 1,
                label: "2",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 2,
                label: "3",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 3,
                label: "r",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 4,
                label: "t",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 5,
                label: "y",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 6,
                label: "u",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 7,
                label: "i",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 8,
                label: "o",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 9,
                label: "p",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 10,
                label: "a",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 11,
                label: "s",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 12,
                label: "d",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 13,
                label: "f",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 14,
                label: "g",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 15,
                label: "h",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 16,
                label: "j",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 17,
                label: "k",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 18,
                label: "l",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 19,
                label: ":",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 20,
                label: "z",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 21,
                label: "x",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 22,
                label: "c",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 23,
                label: "v",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 24,
                label: "b",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 25,
                label: "n",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 26,
                label: "m",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 27,
                label: ",",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 28,
                label: ".",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 29,
                label: "/",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 30,
                label: "1",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 31,
                label: "2",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 32,
                label: "3",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 33,
                label: "4",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 34,
                label: "5",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 35,
                label: "6",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
        ],
    },
]