export const keys = [
    {
        "id": 5212,
        "key_category_id": 61,
        "code": "KC_Y",
        "label": "Y",
        "description": null,
        "created_at": "2021-12-28T09:52:59.133Z",
        "updated_at": "2022-12-16T10:18:29.956Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyY",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5214,
        "key_category_id": 61,
        "code": "KC_Z",
        "label": "Z",
        "description": null,
        "created_at": "2021-12-28T09:52:59.149Z",
        "updated_at": "2022-12-16T10:18:29.972Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyZ",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5199,
        "key_category_id": 61,
        "code": "KC_A",
        "label": "A",
        "description": null,
        "created_at": "2021-12-28T09:52:59.022Z",
        "updated_at": "2022-12-16T10:18:29.845Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyA",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5203,
        "key_category_id": 61,
        "code": "KC_B",
        "label": "B",
        "description": null,
        "created_at": "2021-12-28T09:52:59.057Z",
        "updated_at": "2022-12-16T10:18:29.879Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyB",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5216,
        "key_category_id": 61,
        "code": "KC_C",
        "label": "C",
        "description": null,
        "created_at": "2021-12-28T09:52:59.165Z",
        "updated_at": "2022-12-16T10:18:29.989Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyC",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5206,
        "key_category_id": 61,
        "code": "KC_D",
        "label": "D",
        "description": null,
        "created_at": "2021-12-28T09:52:59.084Z",
        "updated_at": "2022-12-16T10:18:29.906Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyD",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5202,
        "key_category_id": 61,
        "code": "KC_E",
        "label": "E",
        "description": null,
        "created_at": "2021-12-28T09:52:59.049Z",
        "updated_at": "2022-12-16T10:18:29.870Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyE",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5200,
        "key_category_id": 61,
        "code": "KC_F",
        "label": "F",
        "description": null,
        "created_at": "2021-12-28T09:52:59.031Z",
        "updated_at": "2022-12-16T10:18:29.853Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyF",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5208,
        "key_category_id": 61,
        "code": "KC_G",
        "label": "G",
        "description": null,
        "created_at": "2021-12-28T09:52:59.102Z",
        "updated_at": "2022-12-16T10:18:29.923Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyG",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5219,
        "key_category_id": 61,
        "code": "KC_H",
        "label": "H",
        "description": null,
        "created_at": "2021-12-28T09:52:59.191Z",
        "updated_at": "2022-12-16T10:18:30.025Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyH",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5205,
        "key_category_id": 61,
        "code": "KC_I",
        "label": "I",
        "description": null,
        "created_at": "2021-12-28T09:52:59.075Z",
        "updated_at": "2022-12-16T10:18:29.897Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyI",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5210,
        "key_category_id": 61,
        "code": "KC_J",
        "label": "J",
        "description": null,
        "created_at": "2021-12-28T09:52:59.117Z",
        "updated_at": "2022-12-16T10:18:29.940Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyJ",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5224,
        "key_category_id": 61,
        "code": "KC_K",
        "label": "K",
        "description": null,
        "created_at": "2021-12-28T09:52:59.236Z",
        "updated_at": "2022-12-16T10:18:30.076Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyK",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5211,
        "key_category_id": 61,
        "code": "KC_L",
        "label": "L",
        "description": null,
        "created_at": "2021-12-28T09:52:59.125Z",
        "updated_at": "2022-12-16T10:18:29.948Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyL",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5201,
        "key_category_id": 61,
        "code": "KC_M",
        "label": "M",
        "description": null,
        "created_at": "2021-12-28T09:52:59.040Z",
        "updated_at": "2022-12-16T10:18:29.862Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyM",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5222,
        "key_category_id": 61,
        "code": "KC_N",
        "label": "N",
        "description": null,
        "created_at": "2021-12-28T09:52:59.217Z",
        "updated_at": "2022-12-16T10:18:30.056Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyN",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5220,
        "key_category_id": 61,
        "code": "KC_O",
        "label": "O",
        "description": null,
        "created_at": "2021-12-28T09:52:59.200Z",
        "updated_at": "2022-12-16T10:18:30.036Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyO",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5209,
        "key_category_id": 61,
        "code": "KC_P",
        "label": "P",
        "description": null,
        "created_at": "2021-12-28T09:52:59.110Z",
        "updated_at": "2022-12-16T10:18:29.931Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyP",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5218,
        "key_category_id": 61,
        "code": "KC_Q",
        "label": "Q",
        "description": null,
        "created_at": "2021-12-28T09:52:59.183Z",
        "updated_at": "2022-12-16T10:18:30.014Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyQ",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5217,
        "key_category_id": 61,
        "code": "KC_R",
        "label": "R",
        "description": null,
        "created_at": "2021-12-28T09:52:59.175Z",
        "updated_at": "2022-12-16T10:18:29.999Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyR",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5215,
        "key_category_id": 61,
        "code": "KC_S",
        "label": "S",
        "description": null,
        "created_at": "2021-12-28T09:52:59.157Z",
        "updated_at": "2022-12-16T10:18:29.980Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyS",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5223,
        "key_category_id": 61,
        "code": "KC_T",
        "label": "T",
        "description": null,
        "created_at": "2021-12-28T09:52:59.227Z",
        "updated_at": "2022-12-16T10:18:30.066Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyT",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5221,
        "key_category_id": 61,
        "code": "KC_U",
        "label": "U",
        "description": null,
        "created_at": "2021-12-28T09:52:59.208Z",
        "updated_at": "2022-12-16T10:18:30.045Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyU",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5204,
        "key_category_id": 61,
        "code": "KC_V",
        "label": "V",
        "description": null,
        "created_at": "2021-12-28T09:52:59.066Z",
        "updated_at": "2022-12-16T10:18:29.887Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyV",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5207,
        "key_category_id": 61,
        "code": "KC_W",
        "label": "W",
        "description": null,
        "created_at": "2021-12-28T09:52:59.093Z",
        "updated_at": "2022-12-16T10:18:29.914Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyW",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5213,
        "key_category_id": 61,
        "code": "KC_X",
        "label": "X",
        "description": null,
        "created_at": "2021-12-28T09:52:59.142Z",
        "updated_at": "2022-12-16T10:18:29.964Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": "KeyX",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5466,
        "key_category_id": 63,
        "code": "ALL_T",
        "label": "Hyper",
        "description": "Alt+Shift+Ctrl+Cmd\n",
        "created_at": "2021-12-28T09:53:02.759Z",
        "updated_at": "2022-12-16T23:38:29.809Z",
        "deleted": false,
        "modifiable": false,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": 1,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5478,
        "key_category_id": 63,
        "code": "MEH_T",
        "label": "Meh",
        "description": "Alt+Shift+Ctrl\n",
        "created_at": "2021-12-28T09:53:02.951Z",
        "updated_at": "2022-12-16T23:38:29.875Z",
        "deleted": false,
        "modifiable": false,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": 2,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5479,
        "key_category_id": 63,
        "code": "OSM",
        "label": "OSM",
        "description": "One-shot modifier: Turns a modifier on, but only for one keypress. Once you press a key in the modifier is then deactivated. You can keep the modifier active by holding the key down.",
        "created_at": "2021-12-28T09:53:02.966Z",
        "updated_at": "2022-12-16T23:38:29.884Z",
        "deleted": false,
        "modifiable": false,
        "shifted": false,
        "tap": true,
        "hold": false,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": null,
        "geometry": null,
        "params": {
            "modifier": true
        },
        "models": null,
        "priority": 3,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5469,
        "key_category_id": 63,
        "code": "MOD_HYPR",
        "label": "Hyper",
        "description": null,
        "created_at": "2021-12-28T09:53:02.821Z",
        "updated_at": "2022-12-16T10:18:32.015Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": false,
        "hold": false,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5470,
        "key_category_id": 63,
        "code": "MOD_LCTL",
        "label": "Left Control",
        "description": null,
        "created_at": "2021-12-28T09:53:02.833Z",
        "updated_at": "2022-12-16T10:18:32.025Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": false,
        "hold": false,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5474,
        "key_category_id": 63,
        "code": "KC_LCTRL",
        "label": "Left Ctrl",
        "description": null,
        "created_at": "2021-12-28T09:53:02.894Z",
        "updated_at": "2022-12-16T10:18:32.058Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": "control",
        "tag": null,
        "glyph": null,
        "jsCode": "ControlLeft",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5464,
        "key_category_id": 63,
        "code": "MOD_LSFT",
        "label": "Left Shift",
        "description": null,
        "created_at": "2021-12-28T09:53:02.723Z",
        "updated_at": "2022-12-16T10:18:31.964Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": false,
        "hold": false,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5465,
        "key_category_id": 63,
        "code": "KC_LSHIFT",
        "label": "Left shift",
        "description": null,
        "created_at": "2021-12-28T09:53:02.738Z",
        "updated_at": "2022-12-16T10:18:31.972Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": "shift_left",
        "jsCode": "ShiftLeft",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5472,
        "key_category_id": 63,
        "code": "MOD_MEH",
        "label": "Meh",
        "description": null,
        "created_at": "2021-12-28T09:53:02.861Z",
        "updated_at": "2022-12-16T10:18:32.041Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": false,
        "hold": false,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5468,
        "key_category_id": 63,
        "code": "MOD_RCTL",
        "label": "Right Control",
        "description": null,
        "created_at": "2021-12-28T09:53:02.806Z",
        "updated_at": "2022-12-16T10:18:32.006Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": false,
        "hold": false,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5477,
        "key_category_id": 63,
        "code": "KC_RCTRL",
        "label": "Right Ctrl",
        "description": null,
        "created_at": "2021-12-28T09:53:02.936Z",
        "updated_at": "2022-12-16T10:18:32.084Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": "control",
        "tag": null,
        "glyph": null,
        "jsCode": "ControlRight",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5476,
        "key_category_id": 63,
        "code": "MOD_RSFT",
        "label": "Right Shift",
        "description": null,
        "created_at": "2021-12-28T09:53:02.921Z",
        "updated_at": "2022-12-16T10:18:32.075Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": false,
        "hold": false,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5461,
        "key_category_id": 63,
        "code": "KC_RSHIFT",
        "label": "Right shift",
        "description": null,
        "created_at": "2021-12-28T09:53:02.686Z",
        "updated_at": "2022-12-16T10:18:31.939Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": null,
        "tag": null,
        "glyph": "shift_right",
        "jsCode": "ShiftRight",
        "url": null,
        "os": null,
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5467,
        "key_category_id": 63,
        "code": "KC_RALT",
        "label": null,
        "description": "Also known as AltGr.",
        "created_at": "2021-12-28T09:53:02.786Z",
        "updated_at": "2022-12-16T23:38:29.817Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": "altgr option",
        "tag": null,
        "glyph": null,
        "jsCode": "AltRight",
        "url": null,
        "os": {
            "osx": {
                "glyph": "option_right",
                "label": "Right Option (macOS)"
            },
            "others": {
                "label": "Right Alt"
            }
        },
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5471,
        "key_category_id": 63,
        "code": "KC_RGUI",
        "label": null,
        "description": null,
        "created_at": "2021-12-28T09:53:02.847Z",
        "updated_at": "2022-12-16T10:18:32.033Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": "gui cmd command meta windows super",
        "tag": null,
        "glyph": null,
        "jsCode": "MetaRight",
        "url": null,
        "os": {
            "osx": {
                "glyph": "command_right",
                "label": "Right Command"
            },
            "win": {
                "glyph": "windows_right",
                "label": "Right Windows"
            },
            "linux": {
                "glyph": "linux_right",
                "label": "Right Meta"
            }
        },
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5473,
        "key_category_id": 63,
        "code": "MOD_LGUI",
        "label": null,
        "description": null,
        "created_at": "2021-12-28T09:53:02.879Z",
        "updated_at": "2022-12-16T10:18:32.050Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": false,
        "hold": false,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": {
            "osx": {
                "label": "Left Command"
            },
            "win": {
                "label": "Left Windows"
            },
            "linux": {
                "label": "Left Meta"
            }
        },
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5475,
        "key_category_id": 63,
        "code": "MOD_LALT",
        "label": null,
        "description": null,
        "created_at": "2021-12-28T09:53:02.907Z",
        "updated_at": "2022-12-16T10:18:32.067Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": false,
        "hold": false,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": {
            "osx": {
                "label": "Left Option"
            },
            "others": {
                "label": "Left Alt"
            }
        },
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5460,
        "key_category_id": 63,
        "code": "MOD_RALT",
        "label": null,
        "description": "Right Alt, also known as AltGr.",
        "created_at": "2021-12-28T09:53:02.675Z",
        "updated_at": "2022-12-16T23:38:29.778Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": false,
        "hold": false,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": {
            "osx": {
                "glyph": "Right Option",
                "label": "Right Option"
            },
            "others": {
                "label": "Right Alt"
            }
        },
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5459,
        "key_category_id": 63,
        "code": "KC_LALT",
        "label": null,
        "description": null,
        "created_at": "2021-12-28T09:53:02.663Z",
        "updated_at": "2022-12-16T10:18:31.921Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": "option",
        "tag": null,
        "glyph": null,
        "jsCode": "AltLeft",
        "url": null,
        "os": {
            "osx": {
                "glyph": "option_left",
                "label": "Left Option"
            },
            "others": {
                "label": "Left Alt"
            }
        },
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5462,
        "key_category_id": 63,
        "code": "MOD_RGUI",
        "label": null,
        "description": null,
        "created_at": "2021-12-28T09:53:02.698Z",
        "updated_at": "2022-12-16T10:18:31.947Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": false,
        "hold": false,
        "doubleTap": false,
        "tapHold": false,
        "searchLabel": null,
        "tag": null,
        "glyph": null,
        "jsCode": null,
        "url": null,
        "os": {
            "osx": {
                "label": "Right Command"
            },
            "win": {
                "label": "Right Windows"
            },
            "linux": {
                "label": "Right Meta"
            }
        },
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": null,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    },
    {
        "id": 5463,
        "key_category_id": 63,
        "code": "KC_LGUI",
        "label": null,
        "description": null,
        "created_at": "2021-12-28T09:53:02.712Z",
        "updated_at": "2022-12-16T10:18:31.956Z",
        "deleted": false,
        "modifiable": true,
        "shifted": false,
        "tap": true,
        "hold": true,
        "doubleTap": true,
        "tapHold": true,
        "searchLabel": "gui cmd command meta windows super",
        "tag": null,
        "glyph": null,
        "jsCode": "MetaLeft",
        "url": null,
        "os": {
            "osx": {
                "glyph": "command_left",
                "label": "Left Command"
            },
            "win": {
                "glyph": "windows_left",
                "label": "Left Windows"
            },
            "linux": {
                "glyph": "linux_left",
                "label": "Left Meta"
            }
        },
        "geometry": null,
        "params": null,
        "models": null,
        "priority": null,
        "macro": true,
        "shape": null,
        "comboPickable": true,
        "comboTrigger": true
    }
]