export class Layer {
    constructor(label) {
        this.label = label;
        this.bindings = [
            {
                index: 0,
                label: "q",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 1,
                label: "w",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 2,
                label: "e",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 3,
                label: "r",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 4,
                label: "t",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 5,
                label: "y",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 6,
                label: "u",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 7,
                label: "i",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 8,
                label: "o",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 9,
                label: "p",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 10,
                label: "a",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 11,
                label: "s",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 12,
                label: "d",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 13,
                label: "f",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 14,
                label: "g",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 15,
                label: "h",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 16,
                label: "j",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 17,
                label: "k",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 18,
                label: "l",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 19,
                label: ":",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 20,
                label: "z",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 21,
                label: "x",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 22,
                label: "c",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 23,
                label: "v",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 24,
                label: "b",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 25,
                label: "n",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 26,
                label: "m",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 27,
                label: ",",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 28,
                label: ".",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 29,
                label: "/",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 30,
                label: "1",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 31,
                label: "2",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 32,
                label: "3",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 33,
                label: "4",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 34,
                label: "5",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
            {
                index: 35,
                label: "6",
                tapped: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff tapped",
                    modifiers: [],
                },
                held: {
                    code: "&kp Q",
                    label: "Q",
                    description: "button that does stuff held",
                    modifiers: [],
                },
            },
        ]
    }
}